import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
<header>
  <nav>
    <ul>
      <li><a href="/">Home</a></li>

      <li><a href="/films">Films</a></li>
      <li><a href="/internaldata">Internal Data</a></li>
      <li><a href="/externalapi">External Api</a></li>
      <li><a href="/post">Posts from Db</a></li>
    </ul>
  </nav>
</header>
<div>
  {children}
</div>

      </body>
    </html>
  );
}
